/**
 * Copy the compiled RitualPredict ABI into the frontend so the two never drift.
 *
 *   npx hardhat build && npx hardhat run scripts/export-abi.ts
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const artifactPath = resolve(here, "../artifacts/contracts/RitualPredict.sol/RitualPredict.json");
const outputPath = resolve(here, "../../web/src/lib/predict-abi.ts");

const artifact = JSON.parse(await readFile(artifactPath, "utf8")) as { abi: unknown[] };

const file = `// Generated by hardhat/scripts/export-abi.ts — do not edit by hand.
// Regenerate with: cd hardhat && npx hardhat build && npx hardhat run scripts/export-abi.ts

export const predictAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, file, "utf8");

console.log(`Wrote ${artifact.abi.length} ABI entries to ${outputPath}`);
